name = "doctorai-connect"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "doctorai"
database_id = "bd5cf569-0684-41bc-b441-ae6fc66ba509"

[ai]
binding = "AI"

[vars]
CORS_ORIGINS = "http://127.0.0.1:5173,http://localhost:5173"
GEMINI_API_KEY = "AIzaSyCJkoozOmiLcsUFDb6Xk01LJOlfDrxQdjo"

[dev]
port = 8787
